### ISSUE TITLE
analytics+ hotjar

### ISSUE THREAD

**Issue by piskello** [explorerfbk/explorerfbk.github.io#3]

**Comment by piskello** [comment]
questo ci torna utile x la valutazione

**Comment by napo** [comment]
mi dici dove trovo hotjar?

**Comment by piskello** [comment]
https://www.hotjar.com/

**Comment by napo** [comment]
inserito hotjar a nome di napo@fbk.eu
05a205dbb87908ac3f524eab83988eef73d279ee

**Comment by napo** [comment]
@piskello vuoi essere aggiunto in hotjar?

**Comment by piskello** [comment]
si, volentieri!

**Comment by napo** [comment]
DONE
You got mail
