### ISSUE TITLE
budget data view

### ISSUE THREAD

**Issue by napo** [explorerfbk/explorerfbk.github.io#7]
there is to understand the reason of this voice
![mistake](https://user-images.githubusercontent.com/69814/40347914-3c476c58-5da2-11e8-919c-7e8b8c3ed70b.png)

**Comment by piskello** [comment]
Ho l'impressione che sia dovuta ad un dataset corrotto... o non propriamente formattato... possibile?

**Comment by napo** [comment]
confermo
e413b8b7079794a4bee0b705161ce285295edbaf
